version: '3'
services:
  web:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - /opt/docker-compose-mongodb:/counter_app
    links:
      - db:mongodb
    container_name: counterapp_web_2
    depends_on:
      - db
  db:
    image: mongo:3.0.2
    container_name: mongodb
